version: "3"

services:

  # ng-app:
  #   image: frabrooks/vibrant-lighthouse-ng-app:latest
  #   # depends_on: 
  #   #   api:
  #   #     condition: service_healthy
  #   volumes: 
  #     - ./ng-app/dist:/usr/src/app/dist

  api:
    image: frabrooks/vibrant-lighthouse-api:latest
    depends_on: 
      postgres-db:
        condition: service_healthy
    ports:
      - 5001
    environment:
      - DATABASE_HOSTNAME=postgres-db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 5001"
    healthcheck:
      test: curl --fail -s https://api.eisentodo.com || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  nginx-server:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: on-failure
  
  certbot:
    build: ./certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./logs/api:/var/log/cron:rw
    restart: on-failure

volumes: 
  postgres-db:

