version: "3"

services:
  api:
    image: frabrooks/vibrant-lighthouse:latest
    depends_on: 
      postgres-db:
        condition: service_healthy
    ports:
      - 80:8000
    volumes:
      - ./:/usr/src/app:ro
    environment:
      - DATABASE_HOSTNAME=postgres-db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes: 
  postgres-db:

